version: "4.24.2"
services:
  app:  
    build: .
    ports:
      - "8000:8000" 
    links:
      - mongDB 
  mongDB:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=roquebj1  
      - MONGO_INITDB_ROOT_PASSWORD=12345 